name: Py-algo-ds
root: ~/learn/python/algo_ds_python

windows:
  - development:
      layout: even-horizontal
      panes:
        - vim 
        - vim 

  - testing: source venv/bin/activate.fish
  - ci: git s
